services:
  - type: web
    name: intern-attendance
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: PASSWORD_CODE_EMAIL
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: GMAIL_SENDER
        sync: false
      - key: GMAIL_APP_PASSWORD
        sync: false
